packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/client'
  - 'packages/svelte-components'
  - 'packages/svelte-components/package'
  - 'packages/cli'
  - 'packages/site'
  - 'packages/build-scripts'