packages:
  # all packages in subdirs of packages/ and components/
  # - 'packages/client'
  # - 'packages/svelte-components/package'
  # - 'packages/svelte-components'
  # - 'packages/cli'
  # - 'packages/site'
  # - 'packages/build-scripts'
  - 'packages/imtala'